export default {
  TOKEN: 'TOKEN',
  OPENID: 'OPENID',
  UNIONID: 'UNIONID',
  USERID: 'USERID',
  MOBILE: 'MOBILE',
  scene: 'SCENE',
  completeInfo: 'completeInfo',
  realName: 'realName',
  realMobile: 'realMobile',
  longitude: 'longitude',
  latitude: 'latitude',
  idNo: 'idNo',
  isFirst: 'isFirst',
}